### ISSUE TITLE
Tiger Lake compatibility

### ISSUE THREAD

**Issue by mikecrowe** [mauricema/netboot#2]
I'm having some trouble getting the netboot to work on my Tiger Lake RVP board. The same build works within qemu, but on the real
hardware I just get a hang when jumping to the payload:
```
Loading Payload ID UEFI
Loading Component EPLD:UEFI
Registering container EPLD (45 50 4C 44.00 00 00 00)
  00000000: 45 50 4C 44 01 00 70 03-00 88 0A 00 06 00 00 01  *EPLD..p.........*
HASH verification for usage (0x00001000) with Hash Alg (0x2): Success
SignType (0x2) SignSize (0x180)  SignHashAlg (0x2)
RSA verification for usage (0x00001000): Success
HASH verification for usage (0x00000000) with Hash Alg (0x2): Success
Calculate Hash for component Type 0x45 as its not available in Component hash table
PCR (0) extended successfully with (1) event type.
Adding event in TCG event log at : 0x78BF318D
Load Payload ID 0x49464555 @ 0x00B00000
FV Format Payload
SmmRamBase = 0x7B000000, SmmRamSize = 0x800000
SmmRamBase = 0x7B000000, SmmRamSize = 0x800000
SmmRamBase = 0x7B000000, SmmRamSize = 0x800000
MP Init (Done)
Call FspNotifyPhase(40) ... Success
Call FspNotifyPhase(F0) ... Success
HOB @ 0x78C10000
Created 2 OS boot options (Current: 0)
SmmRamBase = 0x7B000000, SmmRamSize = 0x800000
HECI1 MeFirmwareStatus = 4400308
Stage2: HwState 0xF TpmType 0x3
Stage2 stack: 0x40000 (stack used 0xE20, HOB used 0x1698, 0x3DB48 free)
Stage2 heap: 0x4C0000 (0x294A20 used, 0x22B5E0 free, 0x34D235 max used)
Payload entry: 0x00802830
Switch to x64 mode
Jump to payload
```

Is there anywhere I should start with trying to work out why this is? Should netboot even work on Tiger Lake?

Thanks.

Mike.

**Comment by mauricema** [comment]
Hi, Mike,

Yes, it should work on TGL.  I don't have TGL RVP to try, but I did try it on UPXi11 TGL-U board.   I was able to boot to the netboot fine.  Below is the log.
[Debug.log](https://github.com/mauricema/netboot/files/7981526/Debug.log)

**Comment by mauricema** [comment]
Just for your reference, I also attached my netboot payload binary here. It was built with Windows env.
[netboot.zip](https://github.com/mauricema/netboot/files/7981537/netboot.zip)

**Comment by mikecrowe** [comment]
Your payload binary runs successfully (it doesn't actually get an IP address, but I think that's because there's something more fundamentally wrong with Ethernet for me) - thanks for providing it.

This means that my payload binary not working is probably be due to something about how I'm building it on Linux. I shall see if I can work out what. Are you able to build on Linux too in order to confirm that the resulting binary works for you?

Thanks.

Mike.

**Comment by mauricema** [comment]
With Linux build, I did reproduce the failure you observed.   In my case, it is not hang, but reset.  
Let me take a look to see what went wrong.  Will provide updates when I have some findings.

**Comment by mauricema** [comment]
OK, looks like it is a bug in UEFI payload.   Current UEFI payload does not satisfy the stack alignment required by x64.
I applied a workaround here in my patch.  Please try the latest master branch of the netboot, and it should address this issue.
https://github.com/mauricema/netboot/commit/e6f4177cb6e4cb363034861cd339290b7c0cb28f

**Comment by mikecrowe** [comment]
The current master appears to solve the problem for me. The binary I've built works on TGL. Thanks!
